configuration: Release

deploy:
  release: master
  provider: GitHub
  auth_token:
    secure: cxiHYFfint9KkR184q7kzHfxk4WEvRo6QG6IGZ+emXCOviMV/3mOQJqmDxKjIh4e
  draft: false
  prerelease: false
  on:
    branch: master
artifacts: 
  - path: YAWOL\YAWOL\bin\Release\YAWOL.exe