deploy:
  release: yawol-v$(appveyor_build_version)
  provider: GitHub
  auth_token:
    secure: cxiHYFfint9KkR184q7kzHfxk4WEvRo6QG6IGZ+emXCOviMV/3mOQJqmDxKjIh4e
  artifact: YAWOL\YAWOL\bin\Release\YAWOL.exe
  artifact: YAWOL\YAWOL\bin\Release\sqlite3.dll
  draft: false
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: false
