deploy:
  release: yawol-v$(appveyor_build_version)
  provider: GitHub
  auth_token:
    secure: cxiHYFfint9KkR184q7kzHfxk4WEvRo6QG6IGZ+emXCOviMV/3mOQJqmDxKjIh4e
  artifact: yawol.zip
  draft: false
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true
