configuration: Release

deploy:
  release: yawol-v$(appveyor_build_version)
  provider: GitHub
  auth_token:
    secure: cxiHYFfint9KkR184q7kzHfxk4WEvRo6QG6IGZ+emXCOviMV/3mOQJqmDxKjIh4e
  draft: false
  prerelease: false
  on:
    branch: master
after_build: 7z a yawol.zip C:\projects\yawol\YAWOL\YAWOL\bin\Release\YAWOL.exe C:\projects\yawol\YAWOL\YAWOL\bin\Release\sqlite3.dll
artifacts: 
  - path: yawol.zip